services:
  mysql:
    image: mysql:8.0
    container_name: netflux_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netflux
      MYSQL_USER: netflux
      MYSQL_PASSWORD: netflux
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - netflux_network
    command: >
      --default-authentication-plugin=mysql_native_password --skip-name-resolve
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-unetflux", "-pnetflux" ]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    container_name: netflux_backend_dev
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://netflux:netflux@mysql:3306/netflux?serverVersion=8.0
      APP_ENV: dev
      APP_DEBUG: 1
      XDEBUG_MODE: off
    volumes:
      # Monte le code source
      - ./backend:/app
      # EXCLUSIONS des dossiers lourds (volumes nommés à la place)
      - backend_vendor:/app/vendor
      - backend_var:/app/var
    networks:
      - netflux_network

  nginx_backend:
    image: nginx:alpine
    container_name: netflux_nginx_backend_dev
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./backend/public:/app/public:ro
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - netflux_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    container_name: netflux_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - netflux_network

volumes:
  mysql_dev_data:
  backend_vendor:
  backend_var:
  frontend_node_modules:


networks:
  netflux_network:
    driver: bridge
