nelmio_cors:
    defaults:
        origin_regex: true # Si besoin de regex dans le CORS_ALLOW_ORIGIN
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        allow_credentials: true
        expose_headers: ['Link', 'Content-Range']
        max_age: 3600
    paths:
        '^/': null
